### ISSUE TITLE
[FR] VST Plugins PATHs for scanning revamp

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qtractor#372]
Hi @rncbc 
Following our discussion on IRC, here is a case scenario:

I'm using 0.9.30.

System-side's Qtractor.conf is:
```
$ cat /etc/xdg/rncbc.org/Qtractor.conf
[Default]
InstrumentDir=/usr/share/sounds/sf2

[InstrumentFiles]
File1=/usr/share/sounds/sf2/TimGM6mb.sf2
```

I'm removing user-side's Qtractor.conf:
`$ rm ~/.config/rncbc.org/Qtractor.conf`

My env related variables are:
```
$ env |grep -i vst_path
LXVST_PATH=/home/MYUSERNAME/.lxvst:/usr/local/lib/lxvst:/usr/lib/lxvst
VST_PATH=/home/MYUSERNAME/.vst:/usr/local/lib/vst:/usr/lib/vst
```

I'm launching Qtractor now and going options (F12), then on the "Plugins" tab, and I can see this:

![qtractor-vst2paths](https://user-images.githubusercontent.com/8705846/210872289-1fbe8e81-e396-447a-bdb4-995d209aa361.png)

What I would expect to see here, is Qtractor initializing the VST2 search folders from LXVST_PATH + VST_PATH, ie:
```
/home/MYUSERNAME/.lxvst
/usr/local/lib/lxvst
/usr/lib/lxvst
/home/MYUSERNAME/.vst
/usr/local/lib/vst
/usr/lib/vst
```
and not only from the LXVST_PATH as we can see on the screenshot above.

What do you reckon, is it a bug or a feature request?

**Comment by rncbc** [comment]
it's been already fixed in https://github.com/rncbc/qtractor/commit/b15d0a4 [develop]

**Comment by trebmuh** [comment]
Hi Rui.
Maybe I've done something wrong, but rebuilding from 'develop', and I still have the same behavior.

**Comment by rncbc** [comment]
oh crap: I was referring to the fix of the vst3 and clap plugins path aliasing from our irc conversation--that I assume it is fixed.

now, for the lsxvst and vst issue: it's still all working as ever before: ehen defined, LXVST_PATH takes precedence over VST_PATH and that's been long ago settled for compability sake to legacy dssi-vst (cf. README.VST) , I guess it's not really significant  nowadays, mostly due to no one's using dssi-vst anymore if at all :)

so yeah  I'd mark it as a prolly feature request :)
cheers

**Comment by trebmuh** [comment]
Thanks for your quick answer Rui.
OK, I've renamed the issue here to make it a FR.

**Comment by rncbc** [comment]
should this nail it ? https://github.com/rncbc/qtractor/commit/aae174b0c (develop)

**Comment by trebmuh** [comment]
It does, thank you very much.
