### ISSUE TITLE
The new backwards step action goes to before 0, and then jumps to bar 62414.

### ISSUE THREAD

**Issue by toadzroc** [rncbc/qtractor#437]
The new step forward and step backward actions work ok with two caveats., and I put them both in here as they are related.

1. When the step backwards action is used, and the playback cursor goes to before 0 in the timeline, it jumps to bar 62414. Using the fast rewind action restores the position of the PB cursor to the beginning of the project, and stops there, and it cannot go any further, i.e. before zero. (bar 1)
I suggest the same barrier be added to the step backwards action.

2. When any tempo or time signature change is added to the timeline, the step actions become less stable and keep jumping at random to that magic bar number 62414, whether it's the forward or reverse action, and most often occurs when the action is held down. Again, the fast rewind action is pressed, the PB cursor returns to its original position.

**Comment by rncbc** [comment]
maybe fixed in 172b2be

thanks

**Comment by toadzroc** [comment]
Halfway there. The actions don't jump anymore when there's no changes in the timeline.

When there are changes in the timeline, the problem persists.

Making progress.

**Comment by rncbc** [comment]
1. and 2. both fixed in 706896d 

hopefully

**Comment by toadzroc** [comment]
Rui, almost there. I don't see bar 62414 anymore, but when a change of tempo is added to the timeline, the step backward action stops just before the added tempo entry. 

Using the rewind action releases the PB cursor to the start.

![qtractor-actions-1](https://github.com/rncbc/qtractor/assets/101512759/a46355c0-14ee-4e38-88c1-6ddfb92ed95b)

**Comment by rncbc** [comment]
can you tell a minimal set of steps where and when the said bug ("_step backward  stops just before the added tempo entry_")  is showing?

i kinda fail to reproduce this happening

**Comment by toadzroc** [comment]
I've made a really rough video of what's happening. Note the tempo change at bar 4, and the tempo change at bar 5.


https://github.com/rncbc/qtractor/assets/101512759/66ea9d84-d300-4726-a733-f3c8e0d3f244

**Comment by rncbc** [comment]
thanks, maybe a 3rd time is final one: a252bf9 :)

**Comment by toadzroc** [comment]
Yep, it's working now. Many thanks. 

I'll let you know if something else comes up. :)
