### ISSUE TITLE
Unable to start (segfault)

### ISSUE THREAD

**Issue by toddmazierski** [rncbc/qtractor#460]
I'd like to confirm #418 is fixed, but unfortunately I'm no longer able to start Qtractor due to a segfault.

This is the package I've installed (`1.0.0-2`):
https://archlinuxarm.org/packages/aarch64/qtractor

The version of Qt installed is `6.7.2`.

Thank you!

## Backtrace

```
#0  0x0000fffff6d6eddc in ?? () from /usr/lib/libQt6Gui.so.6
#1  0x0000fffff660e740 in QVariant::~QVariant() () from /usr/lib/libQt6Core.so.6
#2  0x0000fffff7ae24b0 in QHeaderView::sectionSizeFromContents(int) const ()
   from /usr/lib/libQt6Widgets.so.6
#3  0x0000fffff7ae1f2c in QHeaderView::sizeHint() const () from /usr/lib/libQt6Widgets.so.6
#4  0x0000fffff7b67de8 in QTreeView::updateGeometries() () from /usr/lib/libQt6Widgets.so.6
#5  0x0000fffff65f3260 in ?? () from /usr/lib/libQt6Core.so.6
#6  0x0000fffff7af26d0 in QHeaderView::viewportEvent(QEvent*) () from /usr/lib/libQt6Widgets.so.6
#7  0x0000fffff657b9c4 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()
   from /usr/lib/libQt6Core.so.6
#8  0x0000fffff778c15c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt6Widgets.so.6
#9  0x0000fffff657bd44 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt6Core.so.6
#10 0x0000fffff77ecc14 in QWidgetPrivate::hideChildren(bool) () from /usr/lib/libQt6Widgets.so.6
#11 0x0000fffff77ecbf0 in QWidgetPrivate::hideChildren(bool) () from /usr/lib/libQt6Widgets.so.6
#12 0x0000fffff77ecbf0 in QWidgetPrivate::hideChildren(bool) () from /usr/lib/libQt6Widgets.so.6
#13 0x0000fffff77ecbf0 in QWidgetPrivate::hideChildren(bool) () from /usr/lib/libQt6Widgets.so.6
#14 0x0000fffff77ed280 in QWidgetPrivate::hide_helper() () from /usr/lib/libQt6Widgets.so.6
#15 0x0000fffff77f34c8 in QWidgetPrivate::setVisible(bool) () from /usr/lib/libQt6Widgets.so.6
#16 0x0000fffff791a8b8 in ?? () from /usr/lib/libQt6Widgets.so.6
#17 0x0000fffff791ab78 in ?? () from /usr/lib/libQt6Widgets.so.6
#18 0x0000fffff7966878 in ?? () from /usr/lib/libQt6Widgets.so.6
#19 0x0000fffff7968758 in ?? () from /usr/lib/libQt6Widgets.so.6
#20 0x0000fffff7958c70 in QMainWindow::restoreState(QByteArray const&, int) ()
   from /usr/lib/libQt6Widgets.so.6
#21 0x0000aaaaaae6c7a0 in ?? ()
#22 0x0000aaaaaab353a4 in ?? ()
#23 0x0000fffff5a28294 in ?? () from /usr/lib/libc.so.6
#24 0x0000fffff5a28378 in __libc_start_main () from /usr/lib/libc.so.6
#25 0x0000aaaaaab36eb0 in ?? ()
```

**Comment by rncbc** [comment]
how can you confirm #418 is fixed when you
- can't even start qtractor...
- still trying v1.0.0 when v1.1.1 is the highly recommended one?

**Comment by toddmazierski** [comment]
Thank you, @rncbc. I will try to build the latest from the source rather than the package.

**Comment by toddmazierski** [comment]
Hi, @rncbc. I've built from source:

```
qtractor --version
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
Qtractor 1.1.1
Qt: 6.7.2
```

Unfortunately, I still have a segfault. Below is a new copy of the backtrace. Thank you!

```
0x0000fffff536eddc in ?? () from /usr/lib/libQt6Gui.so.6
(gdb) bt
#0  0x0000fffff536eddc in ?? () from /usr/lib/libQt6Gui.so.6
#1  0x0000fffff4c0e740 in QVariant::~QVariant() () from /usr/lib/libQt6Core.so.6
#2  0x0000fffff7ae24b0 in QHeaderView::sectionSizeFromContents(int) const ()
   from /usr/lib/libQt6Widgets.so.6
#3  0x0000fffff7ae1f2c in QHeaderView::sizeHint() const () from /usr/lib/libQt6Widgets.so.6
#4  0x0000fffff7b67de8 in QTreeView::updateGeometries() () from /usr/lib/libQt6Widgets.so.6
#5  0x0000fffff4bf3260 in ?? () from /usr/lib/libQt6Core.so.6
#6  0x0000fffff7af26d0 in QHeaderView::viewportEvent(QEvent*) () from /usr/lib/libQt6Widgets.so.6
#7  0x0000fffff4b7b9c4 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()
   from /usr/lib/libQt6Core.so.6
#8  0x0000fffff778c15c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt6Widgets.so.6
#9  0x0000fffff4b7bd44 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt6Core.so.6
#10 0x0000fffff77ecc14 in QWidgetPrivate::hideChildren(bool) () from /usr/lib/libQt6Widgets.so.6
#11 0x0000fffff77ecbf0 in QWidgetPrivate::hideChildren(bool) () from /usr/lib/libQt6Widgets.so.6
#12 0x0000fffff77ecbf0 in QWidgetPrivate::hideChildren(bool) () from /usr/lib/libQt6Widgets.so.6
#13 0x0000fffff77ecbf0 in QWidgetPrivate::hideChildren(bool) () from /usr/lib/libQt6Widgets.so.6
#14 0x0000fffff77ed280 in QWidgetPrivate::hide_helper() () from /usr/lib/libQt6Widgets.so.6
#15 0x0000fffff77f34c8 in QWidgetPrivate::setVisible(bool) () from /usr/lib/libQt6Widgets.so.6
#16 0x0000fffff791a8b8 in ?? () from /usr/lib/libQt6Widgets.so.6
#17 0x0000fffff791ab78 in ?? () from /usr/lib/libQt6Widgets.so.6
#18 0x0000fffff7966878 in ?? () from /usr/lib/libQt6Widgets.so.6
#19 0x0000fffff7968758 in ?? () from /usr/lib/libQt6Widgets.so.6
#20 0x0000fffff7958c70 in QMainWindow::restoreState(QByteArray const&, int) ()
   from /usr/lib/libQt6Widgets.so.6
#21 0x0000aaaaaae08804 in qtractorMainForm::setup(qtractorOptions*) ()
#22 0x0000aaaaaab2c75c in main ()
```

**Comment by toddmazierski** [comment]
Thank you, @rncbc. I've deleted the configuration file. Below is the new backtrace (it is less deep):

```
#0  0x0000fffff536eddc in ?? () from /usr/lib/libQt6Gui.so.6
#1  0x0000fffff4c0e740 in QVariant::~QVariant() () from /usr/lib/libQt6Core.so.6
#2  0x0000fffff7ae24b0 in QHeaderView::sectionSizeFromContents(int) const ()
   from /usr/lib/libQt6Widgets.so.6
#3  0x0000fffff7ae1f2c in QHeaderView::sizeHint() const () from /usr/lib/libQt6Widgets.so.6
#4  0x0000fffff7b67de8 in QTreeView::updateGeometries() () from /usr/lib/libQt6Widgets.so.6
#5  0x0000fffff4bf3260 in ?? () from /usr/lib/libQt6Core.so.6
#6  0x0000fffff7af26d0 in QHeaderView::viewportEvent(QEvent*) () from /usr/lib/libQt6Widgets.so.6
#7  0x0000fffff4b7b9c4 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()
   from /usr/lib/libQt6Core.so.6
#8  0x0000fffff778c15c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt6Widgets.so.6
#9  0x0000fffff4b7bd44 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt6Core.so.6
#10 0x0000fffff77ecc14 in QWidgetPrivate::hideChildren(bool) () from /usr/lib/libQt6Widgets.so.6
#11 0x0000fffff77ecbf0 in QWidgetPrivate::hideChildren(bool) () from /usr/lib/libQt6Widgets.so.6
#12 0x0000fffff77ecbf0 in QWidgetPrivate::hideChildren(bool) () from /usr/lib/libQt6Widgets.so.6
#13 0x0000fffff77ecbf0 in QWidgetPrivate::hideChildren(bool) () from /usr/lib/libQt6Widgets.so.6
#14 0x0000fffff77ed280 in QWidgetPrivate::hide_helper() () from /usr/lib/libQt6Widgets.so.6
#15 0x0000fffff77f34c8 in QWidgetPrivate::setVisible(bool) () from /usr/lib/libQt6Widgets.so.6
#16 0x0000aaaaaae07b28 in qtractorMainForm::setup(qtractorOptions*) ()
#17 0x0000aaaaaab2c75c in main ()
```

**Comment by rncbc** [comment]
have no clue then, there must be something either in the Qt6.7.2, Qtractor ARM64 build (or both)
